name: Genera Keystore Segreto

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Genera il file JKS e convertilo in Base64
        run: |
          keytool -genkey -v -keystore smartplug-release.jks -keyalg RSA -keysize 2048 -validity 10000 -alias smartplug-alias -storepass Miopassword123 -keypass Miopassword123 -dname "CN=SmartPlug, OU=Monitor, O=Home, L=Roma, S=Italia, C=IT"
          echo "=== COPIA LA RIGA QUI SOTTO ==="
          base64 -w 0 smartplug-release.jks
          echo ""
          echo "=== FINE COPIA ==="

